//
// "$Id$"
//
// ... for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_PNG_Image.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/fl_ask.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Text_Editor.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>

class UIMain {
  void init();
public:
  Fl_Double_Window *window_main;
  Fl_Tabs *tab0;
  Fl_Group *tab0_easy;
  Fl_Button *btnEasyAC;
  Fl_Choice *optAB;
  static Fl_Menu_Item menu_optAB[];
  Fl_Choice *optBC;
  static Fl_Menu_Item menu_optBC[];
  Fl_Button *btnEasyCalc;
  Fl_Text_Editor *inA;
  Fl_Text_Editor *inB;
  Fl_Text_Editor *inC;
  Fl_Text_Display *outEasy;
  Fl_Button *btnSave;
  Fl_Menu_Button *btnLoad;
  static Fl_Menu_Item menu_btnLoad[];
  Fl_Group *tab0_adv;
  Fl_Text_Editor *inAdv;
  Fl_Text_Display *outAdv;
  Fl_Round_Button *optIO;
  Fl_Round_Button *optFile;
  Fl_Button *btnAdvOpen;
  Fl_Button *btnAdvSave;
  Fl_Button *btnAdvCalc;
  Fl_Button *btnAdvAC;
  Fl_Group *tab0_set;
  Fl_Button *btnAbout;
  Fl_Output *txtStatus;
  Fl_Output *txtR;
  Fl_Button *btnQuestion;
  Fl_Button *btnStop;
  static void btnAboutCB(Fl_Widget*);
  static void btnQuestionCB(Fl_Widget*);
  UIMain();
  Fl_Text_Buffer tbfAdv; 
  static void optIOCB(Fl_Widget* w,void* ptr);
  Fl_Text_Buffer tbfA; 
  Fl_Text_Buffer tbfB; 
  Fl_Text_Buffer tbfC; 
  Fl_Text_Buffer tbfOut; 
  Fl_Text_Buffer tbfAdvOut; 
  bool useFileIO = false; 
  bool busy = false; 
};
extern unsigned char IconData[2113];
#endif
