//
// "$Id$"
//
// ... for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "gui.h"

Fl_Menu_Item UIMain::menu_optAB[] = {
 {"+", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"*", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"/", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item UIMain::menu_optBC[] = {
 {"+", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"*", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"/", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item UIMain::menu_btnLoad[] = {
 {"A", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"B", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"C", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void UIMain::init() {
  { window_main = new Fl_Double_Window(800, 480, "HRCore Calculator");
    window_main->selection_color(FL_WHITE);
    window_main->user_data((void*)(this));
    window_main->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    window_main->hotspot(window_main);
    { tab0 = new Fl_Tabs(0, 0, 800, 460);
      tab0->box(FL_GTK_UP_BOX);
      tab0->color(FL_BACKGROUND2_COLOR);
      tab0->selection_color((Fl_Color)43);
      { tab0_easy = new Fl_Group(0, 30, 800, 430, "   Easy Mode   ");
        tab0_easy->selection_color(FL_BACKGROUND2_COLOR);
        { btnEasyAC = new Fl_Button(680, 245, 45, 40, "AC");
        } // Fl_Button* btnEasyAC
        { optAB = new Fl_Choice(730, 130, 55, 45, "A __ B:");
          optAB->down_box(FL_BORDER_BOX);
          optAB->menu(menu_optAB);
        } // Fl_Choice* optAB
        { optBC = new Fl_Choice(730, 185, 55, 45, "B __ C:");
          optBC->down_box(FL_BORDER_BOX);
          optBC->menu(menu_optBC);
        } // Fl_Choice* optBC
        { btnEasyCalc = new Fl_Button(740, 245, 45, 40, "=");
        } // Fl_Button* btnEasyCalc
        { inA = new Fl_Text_Editor(50, 45, 615, 70);
          inA->buffer(&tbfA);
          inA->wrap_mode(3,0);
        } // Fl_Text_Editor* inA
        { inB = new Fl_Text_Editor(50, 130, 615, 70);
          inB->buffer(&tbfB);
          inB->wrap_mode(3,0);
        } // Fl_Text_Editor* inB
        { inC = new Fl_Text_Editor(50, 215, 615, 70);
          inC->buffer(&tbfC);
          inC->wrap_mode(3,0);
        } // Fl_Text_Editor* inC
        { outEasy = new Fl_Text_Display(50, 300, 735, 145);
          outEasy->buffer(&tbfOut);
          outEasy->wrap_mode(3,0);
        } // Fl_Text_Display* outEasy
        { Fl_Tile* o = new Fl_Tile(10, 90, 30, 15, "A = ");
          o->end();
        } // Fl_Tile* o
        { Fl_Tile* o = new Fl_Tile(10, 175, 30, 15, "B = ");
          o->end();
        } // Fl_Tile* o
        { Fl_Tile* o = new Fl_Tile(10, 265, 30, 15, "C = ");
          o->end();
        } // Fl_Tile* o
        { Fl_Tile* o = new Fl_Tile(15, 380, 30, 15, " = ");
          o->end();
        } // Fl_Tile* o
        { btnSave = new Fl_Button(675, 85, 115, 30, "Save To");
        } // Fl_Button* btnSave
        { btnLoad = new Fl_Menu_Button(675, 45, 115, 30, "Load To ...");
          btnLoad->menu(menu_btnLoad);
        } // Fl_Menu_Button* btnLoad
        tab0_easy->end();
      } // Fl_Group* tab0_easy
      { tab0_adv = new Fl_Group(0, 30, 800, 430, "   Advanced Mode   ");
        tab0_adv->selection_color(FL_BACKGROUND2_COLOR);
        tab0_adv->hide();
        { inAdv = new Fl_Text_Editor(25, 60, 360, 305, "Input Expression");
          Fl_Group::current()->resizable(inAdv);
          inAdv->buffer(&tbfAdv);
          inAdv->wrap_mode(3,0);
        } // Fl_Text_Editor* inAdv
        { outAdv = new Fl_Text_Display(410, 60, 365, 305, "Result");
          outAdv->buffer(&tbfAdvOut);
          outAdv->wrap_mode(3,0);
        } // Fl_Text_Display* outAdv
        { optIO = new Fl_Round_Button(25, 380, 135, 30, "Use GUI IO");
          optIO->type(102);
          optIO->down_box(FL_ROUND_DOWN_BOX);
          optIO->value(1);
          optIO->callback(optIOCB,this);
        } // Fl_Round_Button* optIO
        { optFile = new Fl_Round_Button(25, 415, 135, 30, "Use File-based IO");
          optFile->type(102);
          optFile->down_box(FL_ROUND_DOWN_BOX);
          optFile->deactivate();
          optFile->callback(optIOCB,this);
        } // Fl_Round_Button* optFile
        { btnAdvOpen = new Fl_Button(515, 385, 50, 50, "@fileopen");
          btnAdvOpen->labelcolor((Fl_Color)30);
        } // Fl_Button* btnAdvOpen
        { btnAdvSave = new Fl_Button(585, 385, 50, 50, "@filesave");
          btnAdvSave->labelcolor((Fl_Color)30);
        } // Fl_Button* btnAdvSave
        { btnAdvCalc = new Fl_Button(655, 385, 50, 50, "@>");
          btnAdvCalc->labelcolor((Fl_Color)30);
        } // Fl_Button* btnAdvCalc
        { btnAdvAC = new Fl_Button(725, 385, 50, 50, "@reload");
          btnAdvAC->labelcolor((Fl_Color)30);
        } // Fl_Button* btnAdvAC
        tab0_adv->end();
      } // Fl_Group* tab0_adv
      { tab0_set = new Fl_Group(0, 30, 800, 420, "   Settings   ");
        tab0_set->selection_color(FL_BACKGROUND2_COLOR);
        tab0_set->hide();
        tab0_set->deactivate();
        { Fl_Group* o = new Fl_Group(40, 58, 710, 210, "Not yet finished!");
          o->end();
        } // Fl_Group* o
        tab0_set->end();
      } // Fl_Group* tab0_set
      tab0->end();
    } // Fl_Tabs* tab0
    { btnAbout = new Fl_Button(735, 0, 65, 30, "About");
      btnAbout->box(FL_FLAT_BOX);
      btnAbout->selection_color((Fl_Color)40);
      btnAbout->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* btnAbout
    { txtStatus = new Fl_Output(0, 461, 620, 19);
      txtStatus->box(FL_THIN_UP_BOX);
      txtStatus->color(FL_BACKGROUND_COLOR);
      txtStatus->value("Ready.");
    } // Fl_Output* txtStatus
    { txtR = new Fl_Output(620, 461, 180, 19);
      txtR->box(FL_THIN_UP_BOX);
      txtR->color(FL_BACKGROUND_COLOR);
      txtR->value("");
    } // Fl_Output* txtR
    { btnQuestion = new Fl_Button(700, 0, 35, 30, "?");
      btnQuestion->box(FL_FLAT_BOX);
      btnQuestion->selection_color((Fl_Color)40);
      btnQuestion->align(Fl_Align(FL_ALIGN_CLIP));
    } // Fl_Button* btnQuestion
    { btnStop = new Fl_Button(645, 0, 50, 30, "Stop");
      btnStop->box(FL_FLAT_BOX);
      btnStop->selection_color((Fl_Color)40);
      btnStop->align(Fl_Align(FL_ALIGN_CLIP));
      btnStop->deactivate();
    } // Fl_Button* btnStop
    window_main->set_non_modal();
    window_main->size_range(800, 480, 800, 480);
    window_main->end();
  } // Fl_Double_Window* window_main
}

void UIMain::btnAboutCB(Fl_Widget*) {
  fl_beep();
      fl_message_title("About HRCore Calculator");
      fl_alert(
          "  This is an example UI project for HRCore,\n"
          "a high-resolution calculating core library,\n"
          "which shows how to use the library actually.\n\n"
          "UI Version: V0.8 ,with HRCore V1.1.0 \n"
      	"GUI by FLTK - https://www.fltk.org/  \n"
          "License: LGPL v3\n\n"
          "     Copyright 2023 Lu Yi, SCUT CS \n");
}

void UIMain::btnQuestionCB(Fl_Widget*) {
  fl_message_title("Help of HRCore Calculator");
  fl_beep(0);
  fl_alert(
  	"Q: How to use the program?\n"
  	"A: The program is designed as two modes, easy mode and advanced mode.\n"
  	"   Easy mode is designed to calculate a simple expression, on this \n"
  	"   version it can only calculate A __ B __ C (__ refer to '+-*/').\n"
  	"   Advanced mode can evaluate a expression and get the result. Note \n"
  	"   that both of them only support for integers, not float or double.\n\n"
  	"Q: Can I pause a calculation?\n"
  	"A: No, but you can just terminate it by clicking the [Stop] button. \n"
  	"   When there are some calculation performing, the program will show\n"
  	"   a dialog to ask you again if you'd close the window.\n\n"
  	"Q: About the precision?\n"
  	"A: On paper there are no precision lost, but without any gurantee!\n\n"
  	
  	"That's all, thanks for using this library and GUI!\n"
  );
}

UIMain::UIMain() {
  init();
  btnAbout->callback(btnAboutCB);
  btnQuestion->callback(btnQuestionCB);
  Fl_PNG_Image defaultIcon(NULL, IconData, sizeof(IconData));
  window_main->icon(&defaultIcon);
}

void UIMain::optIOCB(Fl_Widget* w,void* ptr) {
  UIMain* ui = (UIMain*)ptr;
  ui->useFileIO = ( ui->optFile->value() != 0);
}
unsigned char IconData[2113] = /* binary data included from app.png */
{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,128,0,0,0,128,8,6,0,0,
0,195,62,97,203,0,0,0,1,115,82,71,66,0,174,206,28,233,0,0,0,4,103,65,77,65,0,
0,177,143,11,252,97,5,0,0,0,9,112,72,89,115,0,0,22,37,0,0,22,37,1,73,82,36,
240,0,0,0,21,116,69,88,116,67,111,109,109,101,110,116,0,76,97,118,99,53,55,46,
50,52,46,49,48,50,25,121,4,239,0,0,7,181,73,68,65,84,120,94,237,157,205,111,84,
85,24,135,199,143,104,52,80,27,147,182,192,194,63,193,255,1,72,140,10,132,66,
68,19,136,82,86,186,147,15,23,10,52,109,210,138,5,73,76,116,101,98,98,12,232,
198,232,194,192,20,203,70,54,136,4,101,225,150,149,68,161,237,76,167,45,155,126,
209,215,243,59,51,151,153,194,219,206,189,189,231,158,123,155,243,59,201,147,
153,222,185,247,188,167,239,121,206,153,251,217,150,38,199,122,36,84,38,126,235,
150,169,225,109,50,117,46,92,40,0,5,208,147,19,2,20,128,2,80,0,45,49,161,64,1,
40,0,5,208,18,19,10,20,128,2,80,0,45,49,161,64,1,40,0,5,208,18,19,10,20,128,2,
80,0,45,49,161,64,1,40,0,5,208,18,19,10,20,32,39,1,38,126,237,150,137,242,38,
25,255,165,100,193,123,44,211,214,205,18,10,144,131,0,247,199,186,165,90,126,
81,102,254,58,44,11,203,98,193,123,44,195,103,218,54,89,65,1,188,11,128,145,
223,37,149,177,109,178,32,34,75,75,203,22,188,199,50,124,134,117,244,109,221,67,
1,60,11,48,129,215,114,135,76,223,218,103,186,124,101,193,50,124,102,215,241,
4,5,200,73,128,218,205,221,141,110,111,22,44,163,0,254,241,44,64,183,84,202,
157,82,251,227,141,70,183,55,11,150,225,51,172,163,109,155,5,20,128,2,80,0,45,
49,89,65,1,138,7,5,160,0,122,114,178,128,2,20,15,10,64,1,244,228,100,1,5,40,30,
233,5,176,231,240,187,77,199,161,131,235,157,188,22,213,53,4,192,103,218,54,43,
169,199,177,103,12,83,94,63,112,34,192,89,176,181,241,186,77,170,231,182,102,74,
20,231,81,76,173,77,9,72,39,128,233,128,251,87,77,34,71,187,100,242,114,135,76,
24,38,77,39,174,202,229,78,185,55,250,156,76,255,254,90,163,219,155,5,203,240,
25,214,81,183,109,96,99,32,150,137,137,216,105,36,72,45,128,233,128,202,185,46,
243,218,35,149,51,157,150,218,167,47,103,74,20,199,198,180,177,149,118,37,32,
149,0,24,137,149,203,47,216,243,248,181,155,189,102,20,239,106,195,155,50,123,
227,117,169,253,125,188,209,237,205,130,101,246,51,179,142,190,109,11,38,22,98,
34,118,125,54,88,31,105,5,168,98,20,14,111,150,202,249,87,100,246,251,253,50,
115,97,143,204,92,236,205,22,19,3,177,16,19,177,109,27,148,182,197,37,157,0,229,
77,50,115,251,61,89,108,116,162,207,130,152,136,141,54,104,109,139,67,106,1,
134,95,146,7,63,245,201,124,189,73,94,11,98,34,54,218,160,181,45,46,169,4,192,
181,124,92,206,197,21,61,223,197,94,69,52,97,209,6,173,109,113,72,43,64,165,191,
36,248,205,231,31,250,31,2,136,137,216,104,131,214,182,184,80,128,148,2,60,52,
109,153,91,242,47,0,98,34,118,174,2,240,43,192,124,5,252,124,36,191,175,0,19,59,
215,175,128,245,238,4,78,41,59,129,88,182,97,119,2,63,55,59,129,63,120,220,9,52,
177,16,51,247,157,64,30,6,226,48,208,212,145,219,97,32,98,43,237,74,64,58,1,128,
237,128,230,9,26,253,228,77,19,158,8,74,71,20,167,24,39,130,18,130,14,228,169,
224,98,65,1,40,128,158,156,44,160,0,197,131,2,80,0,61,57,89,64,1,138,7,5,160,0,
122,114,178,128,2,20,15,207,2,152,87,62,24,82,40,114,17,128,143,134,21,7,175,2,
224,236,221,248,104,151,84,199,158,124,56,20,203,240,153,61,195,167,110,235,30,
10,224,93,128,230,227,225,211,45,143,135,227,61,31,15,207,7,239,2,0,254,129,
136,226,144,139,0,69,129,2,80,0,10,160,37,38,20,40,0,5,160,0,90,98,66,129,2,80,
0,10,160,37,38,20,40,0,5,160,0,90,98,66,129,2,80,0,10,160,37,38,20,40,0,5,160,
0,90,98,66,129,2,80,0,10,128,36,4,203,245,110,145,179,155,69,190,8,151,146,29,
1,129,130,206,127,245,192,215,178,253,224,249,96,41,105,211,66,40,96,4,32,9,7,
250,6,131,133,2,80,0,61,57,33,64,1,40,0,5,208,18,19,10,20,128,2,80,0,45,49,161,
64,1,40,0,5,208,18,19,10,20,128,2,80,0,45,49,161,64,1,40,0,5,208,18,19,10,20,
128,2,80,0,45,49,161,64,1,40,0,5,208,18,179,30,170,248,67,201,195,29,82,25,124,
94,170,67,233,255,140,121,43,168,11,117,218,186,77,12,196,210,214,75,10,5,112,
36,128,237,252,129,103,100,166,124,84,230,255,185,33,179,215,206,72,245,212,83,
82,253,108,139,186,126,18,80,7,234,66,157,168,27,49,16,203,133,4,20,192,149,0,
102,84,206,148,143,201,156,136,253,63,54,40,115,255,254,41,227,167,74,166,163,
214,47,1,182,69,29,168,11,5,117,35,6,98,33,166,182,77,18,40,128,35,1,48,53,47,
222,189,110,255,135,77,84,240,151,191,230,255,187,105,70,111,73,38,71,146,75,
128,109,176,45,234,64,93,81,65,12,196,66,76,109,187,36,80,0,87,51,128,249,126,
126,112,109,104,133,0,139,11,139,182,227,230,238,222,146,90,191,153,9,18,72,128,
117,177,13,182,69,29,168,43,42,136,129,88,136,169,109,155,4,23,2,188,117,24,12,
200,190,119,251,189,130,152,136,173,181,41,9,142,246,1,204,14,95,255,211,178,
112,239,246,19,29,150,116,38,88,109,228,71,66,33,6,98,185,216,201,76,43,0,58,
160,247,208,41,217,177,231,132,28,249,96,196,112,86,250,222,31,145,62,243,62,19,
76,221,136,129,88,136,137,216,105,37,112,38,64,205,188,142,159,92,189,227,226,
204,4,107,141,124,252,140,186,17,3,177,138,32,192,222,131,167,229,68,255,87,245,
6,230,80,16,27,109,208,218,22,23,39,2,0,123,168,102,118,218,218,117,224,106,
51,65,187,145,255,72,32,19,195,69,231,131,180,2,236,216,123,220,236,153,54,127,
71,239,197,196,70,27,180,182,197,197,153,0,17,147,35,61,241,58,178,69,130,56,
35,191,46,78,207,138,88,105,73,43,192,246,61,199,234,141,92,142,142,125,60,150,
70,76,180,65,107,91,92,156,11,0,226,119,232,150,248,35,191,69,24,87,164,21,96,
215,219,31,203,197,31,175,214,27,156,67,65,108,180,65,107,91,92,50,17,0,196,153,
9,166,78,151,44,190,71,126,68,90,1,192,206,253,31,201,135,39,191,148,239,46,
92,145,111,190,189,228,5,196,66,76,196,214,218,148,132,204,4,0,237,102,130,185,
59,163,22,188,143,138,143,145,31,225,66,0,208,123,232,180,236,122,231,19,175,
32,166,214,150,164,100,42,0,104,55,19,0,223,35,63,194,149,0,27,153,204,5,0,107,
205,4,81,241,57,242,35,40,128,39,1,64,52,19,204,221,185,98,59,250,241,98,59,223,
124,230,99,228,71,80,0,175,2,212,247,246,227,9,144,253,232,7,20,128,95,1,20,64,
75,140,75,218,29,231,63,46,4,126,110,238,4,102,43,1,5,200,88,128,181,70,62,126,
230,97,224,250,41,252,97,96,156,51,124,241,79,4,101,35,129,11,1,118,238,203,241,
68,144,137,173,181,41,9,153,8,208,110,228,183,30,231,183,59,79,144,229,76,144,
86,0,158,10,86,136,51,242,31,239,208,248,194,184,149,32,173,0,209,197,160,229,
165,214,91,97,252,148,40,102,97,46,6,37,187,28,252,228,113,126,236,153,160,104,
151,131,101,201,182,51,159,178,84,140,203,193,232,16,222,16,226,191,20,230,134,
16,219,25,177,110,9,107,127,134,175,221,76,80,172,91,194,6,164,215,116,64,110,
183,132,153,216,104,131,214,182,184,184,17,32,232,155,66,113,115,102,94,55,133,
166,235,124,224,68,128,246,183,133,39,63,183,191,218,76,128,24,188,45,220,29,
110,102,128,225,14,169,141,30,181,29,133,14,2,174,31,12,137,234,69,12,196,226,
131,33,110,112,34,192,148,249,62,174,14,62,43,179,151,142,202,188,25,157,179,
152,162,157,63,26,54,84,175,219,196,64,44,196,212,214,79,2,5,112,37,0,128,4,102,
84,218,7,56,205,247,179,171,67,53,128,186,80,167,173,27,35,223,81,221,20,192,
165,0,27,16,10,64,1,40,128,150,152,80,160,0,20,128,2,104,137,9,5,10,64,1,40,128,
150,152,80,160,0,20,128,2,104,137,9,5,10,64,1,40,128,150,152,80,160,0,20,128,2,
104,137,9,5,10,64,1,40,128,150,152,80,160,0,20,128,2,104,137,9,5,10,48,40,255,3,
71,98,145,68,128,114,31,185,0,0,0,0,73,69,78,68,174,66,96,130};
